### ISSUE TITLE
Remove unnecessary characters from response string.

### ISSUE THREAD

**Issue by UPetersen** [dabear/SwiftLibreOOPWeb#3]
The oop response string currently looks like this:

>"Hey hop, response received: some value from android: currentBg: 63 FullAlgoResults: {"currenTrend":0,"currentBg":63.0,"currentTime":4568,"historicBg":[{"bg":111.0,"quality":0,"time":4095},{"bg":115.0,"quality":0,"time":4110},{"bg":113 ..."`

Please remove the unnecessary first characters until (inclusive) "FullAlgoResults: ".

Furthermore, please rename `currenTrend` in the response to `currentTrend`.

**Comment by dabear** [comment]
Current trend won't be fixed by me. The first chars will remain like that as long as it's a research tool.
