### ISSUE TITLE
How to get accessToken

### ISSUE THREAD

**Issue by lifematrix** [dabear/SwiftLibreOOPWeb#8]
Hey, thanks for your nice and valuable work.

However,  the access token is needed to access the website <https://libreoopweb.azurewebsites.net/api/>.
How could I require for it?

Thanks!

steven

**Comment by dabear** [comment]
Hi. You would get that from me personally. contact me on gitter. I don't give out access to everyone. So you need to prove somehow that you're trustworthy :)
